Christmas task
VaniaToper/christmas-task pull request #1
Opened 2021-12-21 22:55 UTC by VaniaToper

1. ### Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/christmas-task/christmas-task-part1.md
------------
2. ### Screenshot:
![image](https://user-images.githubusercontent.com/76011241/147007625-6eb0de9e-6023-4045-a809-5ff3ca6db394.png)

------------
3.  ### Deploy: https://christmas-task-vaniatoper.netlify.app/
------------
4. ### Done 21.12.2021 / deadline 21.12.2021
------------
5 ### Score 190/220

- [ ] Сохранение настроек в local storage -10
- [ ] Дополнительный функционал на выбор -20

2021-12-24 10:59 UTC, viskosa requested changes

2021-12-24 10:59 UTC, viskosa commented on src/App.tsx
> +          <Redirect to='/NotFound' />
You also can use <Route path="*" render={() => <NotFound />} /> for catching non existing routes.
It means all routes which are not processed by previous routes will be caught by this one

2021-12-24 10:59 UTC, viskosa commented on src/App.tsx
> +    }}>
is it works? I've thought we should pass context in array: value={[isFav, setIsFav]}

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/Filters.tsx
> +import React, { useContext, useMemo, useState } from 'react';
I would recommend to move this file to the 'pages' folder and remove FiltersPage folder here. It would be better to put all components to the folder 'Components' without dividing them into different folders like 'FiltersPage' etc.

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/Filters.tsx
> +const Filters: React.FC<IProps> = ({ data }) => {
minor comment - you can get the FC from react at string #1 and simply use FC<IProps> here

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +                options={optionsReverse} title={'Sort By'} />
Formatting should looks like this - it is common practice to format such way:
![image](https://user-images.githubusercontent.com/30001516/147296682-99e23074-0311-4750-857b-415bbf5775f1.png)

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +        }} resetFilters={setFilter} />
here as well
It is hard to read code with such formatting, please do like this:
![image](https://user-images.githubusercontent.com/30001516/147296734-14039099-170d-42c2-aebd-849d52f325df.png)

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +      </form>
I would recommend do divide this block to three independent:
1 - block with checkboxes  and their logic 
2 - block with selects  and their logic 
3 - block with sliders and their logic

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +                                        }) => {
It is better to use such code formatting:
![image](https://user-images.githubusercontent.com/30001516/147296944-875205f1-6a13-401d-917e-c2a7c1266f16.png)

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/checkbox/Checkbox.tsx
> +                                 style={{ background: background }} />}
it is very hard to follow the code with such formatting. Please, do like this everywhere:
![image](https://user-images.githubusercontent.com/30001516/147297294-8f6328d6-e219-4d51-9736-a19b0b194a1f.png)

2021-12-24 10:59 UTC, viskosa commented on src/style-dev/nullstyle.scss
> +* {
usually the name of such file is 'reset.scss' or 'default.scss'

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +              <Checkbox type={'color'} key={item.value} value={item.value}
you can pass just type='color' without curly braces here and everywhere

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/checkbox/Checkbox.tsx
> +          <use style={{ transform: `scale(${width})` }}
seems it doesn't work as you pass pixels here, it has to be scale instead.
scale(1.5)

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +        changeFilter(target.checked, target.value);
onChange handler should be moved to the separate variable

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +  const changeFilter = (checked: Boolean, value: string) => {
'boolean' should be written in lowercase

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +    }));
it works opposite way from it should be. When you click on green checkbox, it should take only green toys and render them. If you click green and red checkboxes, it should render only green and red toys

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/FiltersBlock.tsx
> +  const [checkBoxes] = useState({
it's not neccesary to use useState here as you don't use setState function. Just const would be ok

const checkBoxes = {colorFilter: [...], shapeFilter: [...], ...}

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/checkbox/Checkbox.tsx
> +                                 style={{ background: background }} />}
Even better would be move the rendering into separate variable and make decision through switch case. It is more readable

![image](https://user-images.githubusercontent.com/30001516/147342099-40078cb8-f1a0-40eb-b612-673b1d5bede1.png)

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/Filters.tsx
> +};
Do formatting like this, please:
![image](https://user-images.githubusercontent.com/30001516/147343606-9d738dd8-d4d1-48a0-95fa-24e8d6b08d8f.png)

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/Card.tsx
> +                                           }) => {
fix the formatting here please. I left examples below

2021-12-24 10:59 UTC, viskosa commented on src/components/FiltersPage/Card.tsx
> +  const setFavCards = (checked: Boolean, num: string) => {
boolean should be in lowercase everywhere

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/input/Input.tsx
> +             onChange={(e)=>onChange(e.target.value)} value={value} type='text' />
fix formatting please

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/select/Select.tsx
> +  onChange: React.Dispatch<React.SetStateAction<string>>;
I think far all such handlers returning void will be enough
onChange: () => void
onBlaBla: () => void

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/select/Select.tsx
> +};
Formatting should be fixed

2021-12-24 10:59 UTC, viskosa commented on src/components/UI/select/Select.tsx
> +                }}
complex handlers should be stored in separate constants

2021-12-24 11:00 UTC, VaniaToper commented on src/App.tsx
> +    }}>
actually works :D

2022-01-09 17:35 UTC, NProtsenko approved these changes

2022-01-30 15:43 UTC, merged